blacklist = [
    "anal",
    "arsch",
    "arschficker",
    "arschlecker",
    "arschloch",
    "bimbo",
    "bratze",
    "bumsen",
    "bonze",
    "dödel",
    "fick",
    "ficken",
    "flittchen",
    "fotze",
    "fratze",
    "hackfresse",
    "hure",
    "hurensohn",
    "ische",
    "kackbratze",
    "kacke",
    "kacken",
    "kackwurst",
    "kampflesbe",
    "kanake",
    "kimme",
    "lümmel",
    "MILF",
    "möpse",
    "morgenlatte",
    "möse",
    "mufti",
    "muschi",
    "nackt",
    "negger",
    "neger",
    "nigger",
    "niger",
    "nippel",
    "nutte",
    "onanieren",
    "orgasmus",
    "pimmel",
    "pimpern",
    "penis",
    "pinkeln",
    "pissen",
    "pisser",
    "popel",
    "poppen",
    "porno",
    "reudig",
    "rosette",
    "schabracke",
    "schlampe",
    "scheiße",
    "scheiß",
    "scheisser",
    "schiesser",
    "schnackeln",
    "schwanz",
    "schwanzlutscher",
    "schwuchtel",
    "tittchen",
    "titten",
    "vögeln",
    "vollpfosten",
    "wichse",
    "wichsen",
    "wichser"
    ]

def is_blacklisted(text):
    text_lower = text.lower()
    return any(word.lower() in text_lower for word in blacklist)


print(is_blacklisted("Scheiß Stift"))